---
substitutions:
  <<: !include secrets.yaml
  esphome_name: arilux_e27_1
  esphome_platform: ESP8266
  esphome_board: esp01_1m

<<: !include components/common.yaml

binary_sensor:
  - !include components/binary_sensors/status.yaml

text_sensor:
  - !include components/text_sensors/version.yaml

my9231:
  data_pin: GPIO13
  clock_pin: GPIO15

light:
  - platform: rgbw
    name: ${esphome_name}_light
    red: red
    green: green
    blue: blue
    white: white

output:
  - platform: my9231
    id: white
    channel: 0
  - platform: my9231
    id: red
    channel: 3
  - platform: my9231
    id: green
    channel: 2
  - platform: my9231
    id: blue
    channel: 1
