esphomeyaml:
  name: bed_sensor_maarten
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
  password: !secret ota_password

sensor:
  - platform: adc
    pin: A0
    name: "Bed Sensor Maarten"
