---
substitutions:
  <<: !include secrets.yaml
  esphome_name: sonoff_s20_wall_fan
  esphome_platform: ESP8266
  esphome_board: esp01_1m

<<: !include components/common.yaml
<<: !include components/devices/sonoff_s20/light.yaml
<<: !include components/devices/sonoff_s20/output.yaml
<<: !include components/devices/sonoff_s20/switch.yaml

binary_sensor:
  - !include components/binary_sensors/status.yaml
  - !include components/devices/sonoff_s20/binary_sensor.yaml

text_sensor:
  - !include components/text_sensors/version.yaml
