---
substitutions:
  <<: !include secrets.yaml
  esphome_name: sonoff_s20_airco
  esphome_platform: ESP8266
  esphome_board: esp01_1m

<<: !include components/common.yaml

binary_sensor:
  - !include components/binary_sensors/status.yaml
  - platform: gpio
    name: ${esphome_name}_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

text_sensor:
  - !include components/text_sensors/version.yaml

light:
  - platform: monochromatic
    name: ${esphome_name}_green_led
    output: green_led

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

switch:
  - platform: gpio
    name: ${esphome_name}_relay
    id: relay
    pin: GPIO12
