---
substitutions:
  <<: !include secrets.yaml
  esphome_name: sonoff_touch_dressing_room
  esphome_platform: ESP8266
  esphome_board: esp01_1m

<<: !include components/common.yaml
<<: !include components/devices/sonoff_touch/light.yaml
<<: !include components/devices/sonoff_touch/output.yaml
<<: !include components/devices/sonoff_touch/switch.yaml

binary_sensor:
  - !include components/binary_sensors/status.yaml
  - !include components/devices/sonoff_touch/binary_sensor.yaml

text_sensor:
  - !include components/text_sensors/version.yaml
