esphome:
  name: sonoff_s20_airco
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  password: !secret ota_password

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    name: sonoff_s20_airco_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay
  - platform: status
    name: sonoff_s20_airco_status

light:
  - platform: monochromatic
    name: sonoff_s20_airco_green_led
    output: green_led

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

switch:
  - platform: gpio
    name: sonoff_s20_airco_relay
    id: relay
    pin: GPIO12

text_sensor:
  - platform: version
    name: sonoff_s20_airco_version
