---
esphome:
  name: sonoff_basic_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:
  password: !secret ota_password

ota:
  password: !secret ota_password

binary_sensor:
  - platform: gpio
    name: sonoff_basic_1_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: sonoff_basic_1_relay
    id: relay
    pin: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: true

text_sensor:
  - platform: version
    name: sonoff_basic_1_version
