---
substitutions:
  <<: !include secrets.yaml
  esphome_name: sonoff_basic_1
  esphome_platform: ESP8266
  esphome_board: esp01_1m

<<: !include components/common.yaml
<<: !include components/devices/sonoff_basic/switch.yaml
<<: !include components/devices/sonoff_basic/status_led.yaml

binary_sensor:
  - !include components/binary_sensors/status.yaml
  - !include components/devices/sonoff_basic/binary_sensor.yaml

text_sensor:
  - !include components/text_sensors/version.yaml
